name: codelab_final
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  fluttertoast: ^8.2.4
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.17.3
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.5
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  #-------- Local Assets --------#
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/teachers/
    - assets/images/Alumnis/

  #-------- Local Fonts --------#
  fonts:
    # Poppins
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
